version: 2
jobs:
  lint:
    docker:
      - image: endocrimes/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee swiftlint.txt
      - store_artifacts:
          path: swiftlint.txt
  danger:
    docker:
      - image: endocrimes/danger:latest
    steps:
      - checkout
      - run: danger
  build_test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: fastlane scan

workflows:
  version: 2
  build_test_lint:
    jobs:
      - lint
      - danger
      - build_test
